spring.application.name=system-design-ai

spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.main.web-application-type=servlet

spring.web.resources.add-mappings=true

# Integrate openAI key
spring.ai.openai.api-key=${OPENAI_API_KEY}